//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paysheet
    {
        public int Id { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> Chit_num { get; set; }
        public Nullable<int> TruckLic_num { get; set; }
        public Nullable<int> Job_num { get; set; }
        public Nullable<int> DestinationID { get; set; }
        public Nullable<System.DateTime> Date_of_delivery { get; set; }
        public Nullable<int> RateID { get; set; }
        public Nullable<int> DriversID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Destination Destination { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Rate Rate { get; set; }
    }
}
